name: Build and test
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
#        - {
#            name: "Windows Latest MSVC",
#            os: windows-latest,
#            cc: "cl",
#            cxx: "cl",
#            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
#          }
        - {
            name: "Ubuntu Latest gcc",
            os: ubuntu-latest,
            cc: "gcc-10",
            cxx: "g++-10",
          }
        - {
            name: "Ubuntu Latest clang",
            os: ubuntu-latest,
            cc: "clang-12",
            cxx: "clang++-12",
          }
#        - {
#            name: "macOS Latest clang",
#            os: macos-latest,
#            cc: "clang",
#            cxx: "clang++",
#          }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "🏃‍♂️ Running job ${{ matrix.config.name }}."
      - name: Install dependencies
        run: sudo apt-get install -y librange-v3-dev libfmt-dev
      - name: Compiler info
        run: |
            which cmake
            cmake --version
            which ${CXX}
            ${CXX} --version
      - name: Build
        run: |
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            cmake --build .
      - name: Test
        run: |
            ctest .
